// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeployVersion(arg1) {
  return window['go']['main']['App']['DeployVersion'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadData() {
  return window['go']['main']['App']['LoadData']();
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function UpdateVersion(arg1, arg2) {
  return window['go']['main']['App']['UpdateVersion'](arg1, arg2);
}
