// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function DeployVersion(arg1:string):Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetVersion():Promise<string>;

export function LoadData():Promise<main.VersionedData>;

export function LoadState():Promise<boolean>;

export function SaveConfig(arg1:main.Config):Promise<main.Config>;

export function UpdateVersion(arg1:context.Context,arg2:string):Promise<void>;
